import "../globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className={"flex min-h-screen"}>
          <div className={"w-1/2 bg-slate-500"}></div>
          <div className={"w-1/2"}>{children}</div>
        </div>
      </body>
    </html>
  );
}
