import Link from "next/link";
import "../globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen">
          <div
            className={
              "p-4 flex  border-b-2 border-r-purple-200 justify-between items-center"
            }
          >
            <h1>Manage your LMS</h1>
            <h1>Menu</h1>
          </div>
          <div className={"flex h-dvh"}>
            <div
              className={
                "w-40 border-r-2 border-r-purple-200 flex flex-col gap-3"
              }
            >
              <Link className={"block p-2"} href="/admin">
                Dashboard
              </Link>
              <Link className={"block p-2"} href="/admin/courses">
                Courses
              </Link>
              <Link className={"block p-2"} href="/admin/batches">
                Batches
              </Link>
              <Link className={"block p-2"} href="/admin/teachers">
                Teachers
              </Link>
            </div>
            <div className={"flex-grow p-2"}>{children} </div>
          </div>
        </div>
      </body>
    </html>
  );
}
