import Link from "next/link";

export const metadata = {
  title: "LMS | COURSES",
  description: "Generated by create next app",
};
export default function Layout({ children }) {
  return (
    <section>
      <div className="bg-purple-100 py-2 flex gap-3">
        <Link href={"/courses/categories"}>Course Categories</Link>
        <Link href={"/courses/trainers"}>Course Trainers</Link>
      </div>
      {children}
    </section>
  );
}
